permissions: 
  contents: write
  
name: Build Release APKs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Grant Execute Permission for Gradle
        run: chmod +x ./gradlew
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > $GITHUB_WORKSPACE/tetris-app.jks
      - name: Build Release APK
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/tetris-app.jks
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-v1.0.0
          files: app/build/outputs/apk/release/*.apk
